Repository WSU-4110/Novelology, pull requests merged in 2024-03, with the labels that each got.

#100 Replies improvements, and username change fix
  src/components/Posts/CommentComponent.js
  src/pages/Settings.js
Labels: bug, feature, functional, task-sprint1

#128 BookInfo and Sidebar
  src/App.js
  src/components/BookDetailsModal.js
  src/components/BookRating.js
  src/components/BookStacks/AddToBookList.js
  src/components/BookStacks/BookList.js
  src/components/BookStacks/NewBookList.js
  src/components/Card.js
  src/components/NavigationBar.js
  src/components/ReaderProfilePage.js
  src/components/SideBar.js
  src/components/shared/SearchISBN.js
  src/components/shared/searchBook.js
  src/components/user/RolesSelection.js
  src/components/user/SelectGenres.js
  src/functions/AddBook.js
  src/functions/AddRatingToBook.js
  src/functions/CreateBookList.js
  src/pages/BookInfo.js
  src/pages/Profile.js
  src/pages/SearchResults.js
  src/pages/UserOnboarding.js
  src/pages/sampleHome.js
  src/styles/bookSearch.css
  src/styles/sideBar.css
  tailwind.config.js
Labels: bug, enhancement, feature, task-sprint2

#136 Finish styling and functions of notification page
  src/components/NavigationBar.js
  src/components/NotificationItem.js
  src/functions/formatTimeDifference.js
  src/pages/Notifications.js
Labels: feature, functional, task-sprint2

#138 Add appropriate profile display based on the roles a user has selected
  src/App.js
  src/assets/reader-profile-banner.jpg
  src/components/AuthorProfilePage.js
  src/components/ReaderProfilePage.js
  src/components/user/FollowButton.js
  src/components/user/UserOptionsModal.js
  src/functions/reportUser.js
  src/functions/requestFollow.js
  src/functions/toggleFollow.js
  src/functions/toggleMute.js
  src/pages/OldUserPage.js
  src/pages/UserPage.js
Labels: feature, functional, task-sprint2
